const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY="looki.projects.v2";
const examples=["Mechanical keyboard review","Tokyo street-food guide","Beginner photography tutorial","15-minute pasta recipe"];
const state={projects:load(),current:null,stream:null,recorder:null,chunks:[],started:0,timer:null,recognition:null,interim:"",recordings:[]};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const now=()=>new Date().toISOString();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function load(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state.projects));$("#saveState").textContent="Saved just now"}
function toast(s){const e=$("#toast");e.textContent=s;e.classList.add("show");clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove("show"),2600)}
function detect(idea){const s=idea.toLowerCase();if(/food|cook|recipe|pasta/.test(s))return"Food";if(/travel|tokyo|tour|vlog/.test(s))return"Travel";if(/teach|tutorial|how|beginner/.test(s))return"Tutorial";if(/review|unbox|product/.test(s))return"Review";return"Story"}
function planFor(title){const kind=detect(title),sets={Review:[["Hook & product reveal","State the audience and core promise"],["First impressions","Show packaging, design, and setup"],["Key features","Demonstrate the three most important features"],["Real-world test","Capture evidence and honest limitations"],["Verdict","Summarize who should buy it and why"]],Food:[["Finished-dish hook","Open on the final result"],["Ingredients","Overhead layout with quantities"],["Preparation","Show high-value prep details"],["Cook","Capture sound, texture, and timing"],["Plate & taste","Beauty shot and honest reaction"]],Travel:[["Location hook","Establish place and reason to watch"],["Arrival","Wide context and movement"],["First highlight","Details, people, and atmosphere"],["Local insight","Add useful context or a personal story"],["Closing recommendation","Cost, access, and final takeaway"]],Tutorial:[["Outcome hook","Show what viewers will achieve"],["Prerequisites","List tools and starting state"],["Core concept","Explain the mental model simply"],["Walkthrough","Demonstrate each action clearly"],["Check & next step","Verify the result and suggest practice"]],Story:[["Cold open","Lead with tension or the strongest moment"],["Context","Orient the viewer quickly"],["Development","Build the central idea with evidence"],["Payoff","Resolve the question or demonstrate the outcome"],["Close","Leave one memorable takeaway"]]};return{kind,shots:sets[kind].map(([title,description],i)=>({id:uid(),title,description,duration:i===0?20:45,done:false})),script:`HOOK\nWhy should someone watch this video right now?\n\nPROMISE\nTell viewers exactly what they will learn or experience.\n\nBODY\nBuild each point around visible evidence, not just narration.\n\nCLOSE\nSummarize the takeaway and give one clear next step.`,tags:[kind.toLowerCase(),"creator","video"]}}
function createProject(title){const p={id:uid(),title,createdAt:now(),updatedAt:now(),notes:"",markers:[],transcript:[],...planFor(title)};state.projects.unshift(p);save();openProject(p.id)}
function current(){return state.projects.find(p=>p.id===state.current)}
function renderProjects(){const g=$("#projectGrid");g.innerHTML=state.projects.length?state.projects.map(p=>`<article class="project-card" tabindex="0" data-id="${p.id}"><span class="badge">${esc(p.kind)}</span><h3>${esc(p.title)}</h3><p class="muted">${p.shots.length} shots · ${Math.ceil(p.shots.reduce((n,x)=>n+x.duration,0)/60)} min plan</p><span class="meta">Updated ${new Date(p.updatedAt).toLocaleDateString()}</span></article>`).join(""):`<div class="empty"><strong>No projects yet</strong><p>Describe your next video above to build a practical starting plan.</p></div>`}
function openProject(id){state.current=id;const p=current();if(!p)return;$("#projectsView").classList.remove("active");$("#studioView").classList.add("active");$("#projectTitle").value=p.title;$("#projectKind").textContent=p.kind+" project";$("#scriptEditor").value=p.script;$("#projectTags").value=p.tags.join(", ");$("#sessionNotes").value=p.notes||"";renderShots();renderMarkers();renderReview();switchTab("plan")}
function home(){stopMedia();state.current=null;$("#studioView").classList.remove("active");$("#projectsView").classList.add("active");renderProjects()}
function touch(mutator){const p=current();if(!p)return;mutator(p);p.updatedAt=now();save()}
function renderShots(){const p=current();$("#shotList").innerHTML=p.shots.map((s,i)=>`<div class="shot" data-id="${s.id}"><button class="shot-num" data-action="done" aria-label="Mark shot complete">${s.done?"✓":i+1}</button><div><input data-field="title" value="${esc(s.title)}" aria-label="Shot title"><textarea data-field="description" aria-label="Shot description">${esc(s.description)}</textarea></div><div><input data-field="duration" type="number" min="5" max="3600" value="${s.duration}" aria-label="Seconds" title="Duration in seconds"><button class="icon-btn" data-action="remove" aria-label="Remove shot">×</button></div></div>`).join("");$("#runtimeEstimate").textContent=`${Math.ceil(p.shots.reduce((n,s)=>n+Number(s.duration),0)/60)} min estimate`}
function switchTab(name){$$('.tab').forEach(x=>x.classList.toggle("active",x.id===name+"Tab"));$$('.tabs button').forEach(x=>x.classList.toggle("active",x.dataset.tab===name));if(name==="review")renderReview()}
async function enumerate(){if(!navigator.mediaDevices)return;const ds=await navigator.mediaDevices.enumerateDevices();fillSelect("#cameraSelect",ds.filter(x=>x.kind==="videoinput"),"Camera");fillSelect("#micSelect",ds.filter(x=>x.kind==="audioinput"),"Microphone")}
function fillSelect(sel,items,label){const old=$(sel).value;$(sel).innerHTML=items.map((x,i)=>`<option value="${x.deviceId}">${esc(x.label||`${label} ${i+1}`)}</option>`).join("");if(items.some(x=>x.deviceId===old))$(sel).value=old}
async function enableMedia(){try{stopMedia();const v=$("#cameraSelect").value,a=$("#micSelect").value;state.stream=await navigator.mediaDevices.getUserMedia({video:v?{deviceId:{exact:v},width:{ideal:1920},height:{ideal:1080}}:{width:{ideal:1920},height:{ideal:1080}},audio:a?{deviceId:{exact:a},echoCancellation:true,noiseSuppression:true}:true});$("#preview").srcObject=state.stream;await $("#preview").play();$("#cameraEmpty").hidden=true;$("#startRecordBtn").disabled=false;$("#mediaHelp").textContent="Ready. Recording remains in this tab until downloaded.";await enumerate()}catch(e){$("#mediaHelp").textContent=`Media unavailable: ${e.message}`;toast("Could not enable camera or microphone")}}
function bestMime(){return["video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm","video/mp4"].find(x=>MediaRecorder.isTypeSupported(x))||""}
function startRecording(){if(!state.stream)return;state.chunks=[];state.interim="";const mime=bestMime();state.recorder=new MediaRecorder(state.stream,mime?{mimeType:mime,videoBitsPerSecond:5_000_000}:undefined);state.recorder.ondataavailable=e=>{if(e.data.size)state.chunks.push(e.data)};state.recorder.onstop=finishRecording;state.recorder.start(1000);state.started=Date.now();touch(p=>{p.markers=[];p.transcript=[]});$("#startRecordBtn").disabled=true;$("#stopRecordBtn").disabled=false;$("#addMarkerBtn").disabled=false;$("#recordBadge").textContent="● RECORDING";$("#recordBadge").classList.add("live");state.timer=setInterval(updateTimer,250);startSpeech();toast("Recording started")}
function updateTimer(){const s=Math.floor((Date.now()-state.started)/1000);$("#timer").textContent=formatTime(s)}
function stopRecording(){if(state.recorder?.state!=="inactive")state.recorder.stop();stopSpeech();clearInterval(state.timer);$("#stopRecordBtn").disabled=true;$("#addMarkerBtn").disabled=true;$("#recordBadge").textContent="PROCESSING"}
function finishRecording(){const blob=new Blob(state.chunks,{type:state.recorder.mimeType});const rec={id:uid(),blob,url:URL.createObjectURL(blob),createdAt:now(),duration:Math.floor((Date.now()-state.started)/1000),mime:blob.type};state.recordings.unshift(rec);$("#recordBadge").textContent="READY";$("#recordBadge").classList.remove("live");$("#startRecordBtn").disabled=false;renderReview();toast("Recording ready to download")}
function startSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$("#captionOverlay").textContent="Live captions unavailable in this browser";return}const r=state.recognition=new SR();r.continuous=true;r.interimResults=true;r.onresult=e=>{let interim="";for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript.trim();if(e.results[i].isFinal){const end=(Date.now()-state.started)/1000;touch(p=>p.transcript.push({start:Math.max(0,end-Math.max(1,text.split(/\s+/).length/2.4)),end,text}))}else interim+=text}$("#captionOverlay").textContent=interim||current().transcript.at(-1)?.text||""};r.onerror=()=>{};try{r.start()}catch{}}
function stopSpeech(){try{state.recognition?.stop()}catch{}state.recognition=null}
function stopMedia(){if(state.recorder?.state==="recording")stopRecording();state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;if($("#preview"))$("#preview").srcObject=null}
function addMarker(){const seconds=Math.floor((Date.now()-state.started)/1000),label=current().shots[current().markers.length]?.title||`Marker ${current().markers.length+1}`;touch(p=>p.markers.push({id:uid(),seconds,label}));renderMarkers();toast("Chapter marker added")}
function renderMarkers(){const p=current();if(!p)return;$("#markerList").innerHTML=p.markers.length?p.markers.map(m=>`<div class="marker"><span>${esc(m.label)}</span><time>${formatTime(m.seconds)}</time></div>`).join(""):`<p class="muted">Add markers while recording to build chapters.</p>`}
function renderReview(){const p=current();if(!p)return;$("#recordingList").innerHTML=state.recordings.length?state.recordings.map(r=>`<div class="recording"><strong>${new Date(r.createdAt).toLocaleString()}</strong><span class="badge">${formatTime(r.duration)}</span><video controls src="${r.url}"></video><div class="recording-actions"><button class="secondary" data-download-recording="${r.id}">Download recording</button></div></div>`).join(""):`<div class="empty"><strong>No recordings in this tab</strong><p>Recordings are intentionally not retained after this page closes. Download each take you want to keep.</p></div>`;$("#exportSummary").innerHTML=`<strong>${p.shots.length} shots</strong><br>${p.markers.length} chapter markers<br>${p.transcript.length} caption segments<br>${p.tags.length} publishing tags`}
const formatTime=s=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(Math.floor(s%60)).padStart(2,"0")}`;
const srtTime=s=>{const ms=Math.round(s*1000),h=String(Math.floor(ms/3600000)).padStart(2,"0"),m=String(Math.floor(ms%3600000/60000)).padStart(2,"0"),x=String(Math.floor(ms%60000/1000)).padStart(2,"0"),z=String(ms%1000).padStart(3,"0");return`${h}:${m}:${x},${z}`};
function download(data,name,type="text/plain"){const url=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportFile(type){const p=current(),base=p.title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"looki-project";if(type==="json")download(JSON.stringify(p,null,2),`${base}.looki.json`,"application/json");if(type==="txt")download(p.transcript.map(x=>x.text).join("\n"),`${base}-transcript.txt`);if(type==="srt")download(p.transcript.map((x,i)=>`${i+1}\n${srtTime(x.start)} --> ${srtTime(x.end)}\n${x.text}\n`).join("\n"),`${base}.srt`);if(type==="chapters")download(p.markers.map(x=>`${formatTime(x.seconds)} ${x.label}`).join("\n"),`${base}-chapters.txt`);toast("Export created")}
function wire(){examples.forEach(x=>$("#ideaChips").insertAdjacentHTML("beforeend",`<button type="button">${x}</button>`));$("#ideaChips").onclick=e=>{if(e.target.tagName==="BUTTON")$("#idea").value=e.target.textContent};$("#ideaForm").onsubmit=e=>{e.preventDefault();createProject($("#idea").value.trim());e.target.reset()};$("#projectGrid").onclick=e=>{const c=e.target.closest("[data-id]");if(c)openProject(c.dataset.id)};$("#projectGrid").onkeydown=e=>{if((e.key==="Enter"||e.key===" ")&&e.target.dataset.id)openProject(e.target.dataset.id)};$("#homeBtn").onclick=home;$$('.tabs button,[data-go]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab||b.dataset.go));$("#projectTitle").oninput=e=>touch(p=>p.title=e.target.value);$("#scriptEditor").oninput=e=>touch(p=>p.script=e.target.value);$("#projectTags").onchange=e=>touch(p=>p.tags=e.target.value.split(",").map(x=>x.trim()).filter(Boolean));$("#sessionNotes").oninput=e=>touch(p=>p.notes=e.target.value);$("#addShotBtn").onclick=()=>{touch(p=>p.shots.push({id:uid(),title:"New shot",description:"Describe the visual goal",duration:30,done:false}));renderShots()};$("#shotList").oninput=e=>{const row=e.target.closest(".shot"),s=current().shots.find(x=>x.id===row.dataset.id);touch(()=>s[e.target.dataset.field]=e.target.dataset.field==="duration"?Number(e.target.value):e.target.value);renderRuntime()};$("#shotList").onclick=e=>{const row=e.target.closest(".shot");if(!row)return;if(e.target.dataset.action==="remove"){touch(p=>p.shots=p.shots.filter(x=>x.id!==row.dataset.id));renderShots()}if(e.target.dataset.action==="done"){const s=current().shots.find(x=>x.id===row.dataset.id);touch(()=>s.done=!s.done);renderShots()}};$("#enableMediaBtn").onclick=enableMedia;$("#cameraSelect").onchange=enableMedia;$("#micSelect").onchange=enableMedia;$("#startRecordBtn").onclick=startRecording;$("#stopRecordBtn").onclick=stopRecording;$("#addMarkerBtn").onclick=addMarker;$$('[data-export]').forEach(b=>b.onclick=()=>exportFile(b.dataset.export));$("#exportProjectBtn").onclick=()=>exportFile("json");$("#recordingList").onclick=e=>{const id=e.target.dataset.downloadRecording,r=state.recordings.find(x=>x.id===id);if(r)download(r.blob,`looki-recording-${Date.now()}.${r.mime.includes("mp4")?"mp4":"webm"}`,r.mime)};$("#importBtn").onclick=()=>$("#importInput").click();$("#importInput").onchange=importProject;$("#deleteProjectBtn").onclick=async()=>{const d=$("#confirmDialog");d.showModal();d.onclose=()=>{if(d.returnValue==="confirm"){state.projects=state.projects.filter(p=>p.id!==state.current);save();home();toast("Project deleted")}}};window.addEventListener("beforeunload",stopMedia)}
function renderRuntime(){const p=current();$("#runtimeEstimate").textContent=`${Math.ceil(p.shots.reduce((n,s)=>n+Number(s.duration||0),0)/60)} min estimate`}
async function importProject(e){try{const p=JSON.parse(await e.target.files[0].text());if(!p.title||!Array.isArray(p.shots))throw Error("Not a Looki project");p.id=uid();p.updatedAt=now();state.projects.unshift(p);save();renderProjects();toast("Project imported")}catch(err){toast(err.message)}finally{e.target.value=""}}
wire();renderProjects();enumerate().catch(()=>{});if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("./sw.js").catch(()=>{});
