from __future__ import annotations

import hashlib
import json
from pathlib import Path
from textwrap import dedent
import zipfile

ROOT = Path('/mnt/data')
AGENT_SRC = ROOT / 'arc_agi3_braille_my_agent.py'
NOTEBOOK_PATH = ROOT / 'arc_agi3_braille_sigil_scored_run.ipynb'
KERNEL_METADATA_PATH = ROOT / 'kernel-metadata-braille-sigil.json'
BUNDLE_PATH = ROOT / 'arc_agi3_braille_sigil_scored_notebook_bundle.zip'
ACCELERATOR = 't4'
ACCELERATORS = {
    'cpu': {'name': 'none', 'gpu': False},
    't4': {'name': 'nvidiaTeslaT4', 'gpu': True},
    'p100': {'name': 'nvidiaTeslaP100', 'gpu': True},
    'rtx6000': {'name': 'nvidiaRtx6000', 'gpu': True},
}


def code_cell(source: str) -> dict:
    return {
        'cell_type': 'code',
        'metadata': {'trusted': True},
        'outputs': [],
        'execution_count': None,
        'source': source,
    }


def markdown_cell(source: str) -> dict:
    return {'cell_type': 'markdown', 'metadata': {}, 'source': source}


def main() -> None:
    if not AGENT_SRC.exists():
        raise SystemExit(f'Missing agent source: {AGENT_SRC}')
    agent_body = AGENT_SRC.read_text(encoding='utf-8')
    sha = hashlib.sha256(agent_body.encode('utf-8')).hexdigest()
    accel = ACCELERATORS[ACCELERATOR]

    install_cell = code_cell(
        "!pip install --no-index --find-links \\\n"
        " /kaggle/input/competitions/arc-prize-2026-arc-agi-3/arc_agi_3_wheels \\\n"
        " arc-agi python-dotenv\n"
    )

    write_agent_cell = code_cell("%%writefile /tmp/my_agent.py\n" + agent_body)

    verify_cell = code_cell(dedent(f"""\
        import ast
        import hashlib
        from pathlib import Path
        agent_path = Path('/tmp/my_agent.py')
        src = agent_path.read_text(encoding='utf-8')
        parsed = ast.parse(src, filename=str(agent_path))
        class_names = [node.name for node in parsed.body if isinstance(node, ast.ClassDef)]
        assert 'MyAgent' in class_names, 'agent file must define class MyAgent'
        actual_sha = hashlib.sha256(src.encode('utf-8')).hexdigest()
        expected_sha = '{sha}'
        assert actual_sha == expected_sha, (actual_sha, expected_sha)
        compile(src, str(agent_path), 'exec')
        print('Braille-Sigil MyAgent written and compile-verified:', agent_path)
        print('Agent SHA256:', actual_sha)
    """))

    registry_py = dedent("""\
        from typing import Type
        from dotenv import load_dotenv
        from .agent import Agent, Playback
        from .swarm import Swarm
        from .templates.random_agent import Random
        from .templates.my_agent import MyAgent

        load_dotenv()

        AVAILABLE_AGENTS: dict[str, Type[Agent]] = {
            'random': Random,
            'myagent': MyAgent,
        }
    """)
    env_text = dedent("""\
        SCHEME=http
        HOST=gateway
        PORT=8001
        ARC_API_KEY=test-key-123
        ARC_BASE_URL=http://gateway:8001/
        OPERATION_MODE=online
        ENVIRONMENTS_DIR=
        RECORDINGS_DIR=/kaggle/working/server_recording
    """)

    run_cell = code_cell(dedent(f"""\
        import os

        if os.getenv('KAGGLE_IS_COMPETITION_RERUN'):
            # Wait for the ARC-AGI-3 gateway sidecar to become ready.
            !curl --fail --retry 999 --retry-all-errors --retry-delay 5 \\
              --retry-max-time 600 http://gateway:8001/api/games

            # Copy the official framework into writable Kaggle working storage.
            !cp -r /kaggle/input/competitions/arc-prize-2026-arc-agi-3/ARC-AGI-3-Agents \\
              /kaggle/working/ARC-AGI-3-Agents

            # Install this exact agent as a framework template.
            !cp /tmp/my_agent.py \\
              /kaggle/working/ARC-AGI-3-Agents/agents/templates/my_agent.py

            # Register only the minimal required agents to avoid eager optional dependency imports.
            with open('/kaggle/working/ARC-AGI-3-Agents/agents/__init__.py', 'w', encoding='utf-8') as f:
                f.write({registry_py!r})

            # Point the framework at the Kaggle gateway sidecar. The gateway records
            # actions and writes the competition submission.parquet.
            with open('/kaggle/working/ARC-AGI-3-Agents/.env', 'w', encoding='utf-8') as f:
                f.write({env_text!r})

            !cd /kaggle/working/ARC-AGI-3-Agents && \\
              MPLBACKEND=agg \\
              python main.py --agent myagent
    """))

    dummy_cell = code_cell(dedent("""\
        import os

        if not os.getenv('KAGGLE_IS_COMPETITION_RERUN'):
            # Save & Run All / commit mode: emit a valid dummy parquet so Kaggle
            # accepts the notebook commit. The real scored submission.parquet is
            # generated by the gateway during the competition rerun.
            import pandas as pd
            submission = pd.DataFrame(
                data=[['1_0', '1', True, 1]],
                columns=['row_id', 'game_id', 'end_of_game', 'score'],
            )
            submission.to_parquet('/kaggle/working/submission.parquet', index=False)
            print('Commit-mode dummy submission written to /kaggle/working/submission.parquet')
            submission.head()
    """))

    notebook = {
        'metadata': {
            'kernelspec': {
                'language': 'python',
                'display_name': 'Python 3',
                'name': 'python3',
            },
            'language_info': {
                'name': 'python',
                'mimetype': 'text/x-python',
                'file_extension': '.py',
                'pygments_lexer': 'ipython3',
            },
            'kaggle': {
                'accelerator': accel['name'],
                'isInternetEnabled': False,
                'isGpuEnabled': accel['gpu'],
                'language': 'python',
                'sourceType': 'notebook',
            },
        },
        'nbformat_minor': 4,
        'nbformat': 4,
        'cells': [
            markdown_cell(
                '# ARC Prize 2026 — ARC-AGI-3 Braille-Sigil Scored Run\n\n'
                'This notebook embeds the exact `Nine1Eight Braille-Sigil ARC-AGI-3 agent` source. '
                'It follows the official Kaggle Starter submission shape: offline wheel install, write `/tmp/my_agent.py`, '
                'register `MyAgent`, run the ARC gateway rerun, and let the gateway emit `submission.parquet`.\n\n'
                f'Embedded agent SHA256: `{sha}`.'
            ),
            install_cell,
            write_agent_cell,
            verify_cell,
            run_cell,
            dummy_cell,
        ],
    }

    NOTEBOOK_PATH.write_text(json.dumps(notebook, indent=1), encoding='utf-8')

    kernel_meta = {
        'id': 'nine1eight/arc-agi-3-braille-sigil-scored-run',
        'title': 'ARC-AGI-3 Braille-Sigil Scored Run',
        'code_file': str(NOTEBOOK_PATH.name),
        'language': 'python',
        'kernel_type': 'notebook',
        'is_private': True,
        'enable_gpu': accel['gpu'],
        'enable_internet': False,
        'dataset_sources': ['arc-prize-2026-arc-agi-3'],
        'competition_sources': ['arc-prize-2026-arc-agi-3'],
        'keywords': ['arc-agi-3', 'arc-prize-2026', 'braille-sigil', 'nine1eight'],
    }
    KERNEL_METADATA_PATH.write_text(json.dumps(kernel_meta, indent=2) + '\n', encoding='utf-8')

    with zipfile.ZipFile(BUNDLE_PATH, 'w', compression=zipfile.ZIP_DEFLATED) as zf:
        zf.write(NOTEBOOK_PATH, NOTEBOOK_PATH.name)
        zf.write(AGENT_SRC, 'agent/my_agent.py')
        zf.write(KERNEL_METADATA_PATH, 'notebooks/kernel-metadata.json')
        zf.write(Path(__file__), 'scripts/build_braille_kaggle_notebook.py')

    print('notebook', NOTEBOOK_PATH)
    print('kernel_metadata', KERNEL_METADATA_PATH)
    print('bundle', BUNDLE_PATH)
    print('sha256', sha)


if __name__ == '__main__':
    main()
